version: '3'
services:
  web:
    image: nginx:alpine
    container_name: "web"
    volumes:
      - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./etc/ssl:/etc/ssl"
      - "./:/var/www/html"
      - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
    command: /bin/sh -c "envsubst 'localhost' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
    depends_on:
      - php
      - mysql
  php:
    image: nanoninja/php-fpm:latest
    restart: always
    container_name: "php"
    volumes:
      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "./:/var/www/html"
  composer:
    image: "composer"
    volumes:
      - "./:/var/www/html"
    working_dir: /var/www/html
    command: composer install -d /var/www/html
  mysql:
    container_name: "mysql"
    image: library/mysql:5.6.47
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./etc/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      AUTO_INCREMENT: 1

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql
